// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABnwfJ-LwRdkfTpkJ6W6vF2Lsz4xvdu3s',
    appId: '1:525701234509:web:d00e9b36f120b94ef54104',
    messagingSenderId: '525701234509',
    projectId: 'foodorderingapp-aa7f2',
    authDomain: 'foodorderingapp-aa7f2.firebaseapp.com',
    storageBucket: 'foodorderingapp-aa7f2.appspot.com',
    measurementId: 'G-YTBE1L0S49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Cu13cexRpo08mu-vPGQ-D4A9AILAuAE',
    appId: '1:525701234509:android:0c0805d5b3485261f54104',
    messagingSenderId: '525701234509',
    projectId: 'foodorderingapp-aa7f2',
    storageBucket: 'foodorderingapp-aa7f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnRYpiv3IiL-2Tw8NiHixtg8TaSGul9E',
    appId: '1:525701234509:ios:14afe604960860daf54104',
    messagingSenderId: '525701234509',
    projectId: 'foodorderingapp-aa7f2',
    storageBucket: 'foodorderingapp-aa7f2.appspot.com',
    iosBundleId: 'com.example.foodorderingapp',
  );
}
